# This is a basic workflow to help you get started with Actions

name: Bump Version

# Controls when the action will run.
on:
  push:
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Automated Github Action Version Bump'
      uses: 'rimonhanna/gh-action-bump-version@master'
      with:
        tag-prefix: ''

    - name: 'Print package.json'
      run: cat $GITHUB_WORKSPACE/package.json

    - name: 'Print current version'
      run: echo $(npm run env | grep npm_package_version | cut -d '=' -f 2)

    - name: 'Save current version'
      run: echo "PACKAGE_VERSION=$(npm run env | grep npm_package_version | cut -d '=' -f 2)" >> $GITHUB_ENV

    - name: 'Print version'
      run: echo $PACKAGE_VERSION

